### ISSUE TITLE
ToolTip refIcon

### ISSUE THREAD

**Issue by recon2710** [carbon-design-system/carbon-components-svelte#1588]
I needed to change color of tooltip icon. There doesnt seem to be a prop so went about setting ref and changing fill on el. Noticed the ToolTip refIcon reference is not targeting SVG element, but rather the outer div; not sure if thats by design. Let me know if this is not the correct way of going about changing icon fill.

**Comment by metonym** [comment]
> refIcon reference is not targeting SVG element

Unfortunately, this is because `svelte:component` is used to render the icon. Binding to `this` on `svelte:component` references the Svelte component instance, not the DOM element.

You're approach is valid, but personally I'd recommend customizing the color using CSS. There are a couple of ways:

### 1) Global CSS

```svelte
<script>
  import { Tooltip } from "carbon-components-svelte";
</script>

<style>
  :global(.bx--tooltip__trigger svg) {
    fill: red;
  }
</style>

<Tooltip>
  <p>Resources are provisioned based on your account's organization.</p>
</Tooltip>
```

### 2) Icon slot + fill/stroke attributes (more declarative)

```svelte
<script>
  import { Tooltip } from "carbon-components-svelte";
  import { Information } from "carbon-icons-svelte";
</script>

<Tooltip>
  <svelte:fragment slot="icon">
    <Information stroke="blue" />
  </svelte:fragment>
  <p>Resources are provisioned based on your account's organization.</p>
</Tooltip>
```

**Comment by recon2710** [comment]
Got it. Thanks.
