### ISSUE TITLE
TreeView ignores expanded property in children object

### ISSUE THREAD

**Issue by cubic3d** [carbon-design-system/carbon-components-svelte#1630]
Docs on TreeView [here](https://carbon-components-svelte.onrender.com/components/TreeView#with-icons) provide an example with `expanded: true` property to expand the tree element - this element is ignored by TreeView and the child is not expanded.

This behaviour can be seen directly in the example in the docs itself:
![image](https://user-images.githubusercontent.com/4047015/212699182-86a0b35e-a272-42ff-b820-344e87abe524.png)

**Comment by metonym** [comment]
Nice catch. Agreed that at a minimum the docs should be updated.

However, I think the `expanded` prop in `TreeViewNodeList` can be removed entirely since it sets `expanded` based on the `expandedIds` from `TreeView` anyway:

https://github.com/carbon-design-system/carbon-components-svelte/blob/6d2e21f02798c5764484ee5e49bd9f122a429d07/src/TreeView/TreeViewNodeList.svelte#L64

**Comment by theetrain** [comment]
This has been released in [v0.72.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.72.0).
