### ISSUE TITLE
Button with icon only - always shows tooltip

### ISSUE THREAD

**Issue by Sahasrara** [carbon-design-system/carbon-components-svelte#1882]
There seems to be no way to disable the tooltip for buttons that only have an icon. I figured it might be a bug, so I opened this ticket. Feel free to close it if this is by design.

**Comment by brunnerh** [comment]
If there is no label, the tooltip is required for accessibility.

[Spec](https://carbondesignsystem.com/components/button/accessibility#behavior):
> Icon-only buttons, which do not persistently display a text label, expose their label on hover and focus.

**Comment by metonym** [comment]
@brunnerh is exactly correct. See also the [upstream Carbon issue](https://github.com/carbon-design-system/carbon/issues/8805), in which this is an intentional implementation.

Although not recommended for accessibility reasons, if **you must** hide the tooltip, you can always had custom CSS to achieve this. See https://github.com/carbon-design-system/carbon-components-svelte/discussions/1483#discussioncomment-3586643
