### ISSUE TITLE
Tabs issue on responsive / mobile

### ISSUE THREAD

**Issue by ispyinternet** [carbon-design-system/carbon-components-svelte#626]
You can observe this on the documentation site, either on mobile, or using dev tools in responsive mode, if you click on the actual a link with the `href='#'` you get an undesirable navigation to the top of the current page - its fine if you click the `li` avoiding the `a` tag

**Comment by brunnerh** [comment]
Noticed this as well. The problem is probably that the click handlers lack `preventDefault`:

```svelte
<!-- Tabs.svelte -->
    <a
      tabindex="-1"
      class:bx--tabs-trigger-text="{true}"
      href="{triggerHref}"
      on:click
      on:click="{() => {
        dropdownHidden = !dropdownHidden;
      }}"
    >
```

In the larger view the tabs also have an `href="#"` by default, but here the click handlers on `li` have `preventDefault`:

```svelte
<!-- Tab.svelte -->
<li
  tabindex="-1"
  role="presentation"
  class:bx--tabs__nav-item="{true}"
  class:bx--tabs__nav-item--disabled="{disabled}"
  class:bx--tabs__nav-item--selected="{selected}"
  {...$$restProps}
  on:click|preventDefault
  on:click|preventDefault="{() => {
    if (!disabled) {
      update(id);
    }
  }}"
  ...
```

Unfortunately setting the `triggerHref` property on `Tabs` to something like `javascript:void 0` only prevents the navigation, but the dropdown is not opened.

Also, the React version scrolls its tabs instead of collapsing into a dropdown (which seems inferior, but is inconsistent).
