### ISSUE TITLE
uishell: move menu icon

### ISSUE THREAD

**Issue by zfranco55** [carbon-design-system/carbon-components-svelte#830]
I'm trying to understand the carbon bookcase for quick, but on the internet I have not found any tutorials or examples of how to use it. it looks like a beautiful library to me, but for expert use.
I would like to know if is it possible to move the menu icon and its slider to the right side and add a logo (image) on the left?

**Comment by metonym** [comment]
You can try using overriding the icon for the `HeaderAction` component.

Example: https://svelte.dev/repl/95daac35c602418981a85fd9e9f46e4a

**Comment by zfranco55** [comment]
thanks for the replay.
since i'm not an expert, could you tell me how to change the background
color?
Black is fine for carbon, but I would like something more cheerful and not
figured out where to put the class bx - header: xxxxx

Il giorno ven 8 ott 2021 alle ore 22:57 Eric Liu ***@***.***>
ha scritto:

**Comment by metonym** [comment]
You will need to override the CSS because the UI Shell is currently not theme-able.

```svelte
<style>
  :global(.bx--header.bx--header) {
    background-color: red;
    border-bottom-color: red;
   }
</style>
```

I would recommend inspecting the CSS using a browser's developer tools to identify the selector to target. In the example above, we do `.class.class` to use a higher specificity. Using `!important` would also work.
